import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Global } from "@/nilai_global/global";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"></link>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Global>
             {children}
        </Global>
      
      </body>
    </html>
  );
}
